# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Application(object):
    def setupUi(self, Application):
        Application.setObjectName("Application")
        Application.resize(1080, 600)
        Application.setMinimumSize(QtCore.QSize(1080, 600))
        Application.setMaximumSize(QtCore.QSize(1080, 600))
        Application.setMouseTracking(True)
        Application.setStyleSheet("background-color:rgb(32, 38, 52);")
        Application.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(Application)
        self.centralwidget.setMinimumSize(QtCore.QSize(1080, 600))
        self.centralwidget.setMaximumSize(QtCore.QSize(1050, 600))
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setStyleSheet("background-color:rgb(32, 38, 52);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolButton_import_content = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_import_content.setMinimumSize(QtCore.QSize(120, 38))
        self.toolButton_import_content.setMaximumSize(QtCore.QSize(120, 38))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolButton_import_content.setFont(font)
        self.toolButton_import_content.setStyleSheet("QToolButton {\n"
"    color:white; \n"
"    background:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0,         stop:0 rgba(32, 38, 52, 255), \n"
"        stop:1 rgba(91, 99, 120, 255));\n"
"    border: 2px solid black;\n"
"    border-radius: 8px;\n"
"}")
        self.toolButton_import_content.setObjectName("toolButton_import_content")
        self.horizontalLayout.addWidget(self.toolButton_import_content)
        self.lineEdit_import_content = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_import_content.setEnabled(False)
        self.lineEdit_import_content.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_import_content.setStyleSheet("QLineEdit {\n"
"    border-radius: 4px;\n"
"    background-color:rgb(83, 89, 110);\n"
"    color:white;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    border-radius: 4px;\n"
"    background-color:rgb(83, 89, 110);\n"
"    color:rgb(200, 200, 200);\n"
"    border: 0px solid black;\n"
"}")
        self.lineEdit_import_content.setObjectName("lineEdit_import_content")
        self.horizontalLayout.addWidget(self.lineEdit_import_content)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.toolButton_import_style = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_import_style.setMinimumSize(QtCore.QSize(120, 38))
        self.toolButton_import_style.setMaximumSize(QtCore.QSize(120, 38))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolButton_import_style.setFont(font)
        self.toolButton_import_style.setStyleSheet("QToolButton {\n"
"    color:white; \n"
"    background:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0,         stop:0 rgba(32, 38, 52, 255), \n"
"        stop:1 rgba(91, 99, 120, 255));\n"
"    border: 2px solid black;\n"
"    border-radius: 8px;\n"
"}")
        self.toolButton_import_style.setObjectName("toolButton_import_style")
        self.horizontalLayout_5.addWidget(self.toolButton_import_style)
        self.lineEdit_import_style = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_import_style.setEnabled(False)
        self.lineEdit_import_style.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_import_style.setStyleSheet("QLineEdit {\n"
"    border-radius: 4px;\n"
"    background-color:rgb(83, 89, 110);\n"
"    color:white;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    border-radius: 4px;\n"
"    background-color:rgb(83, 89, 110);\n"
"    color:rgb(200, 200, 200);\n"
"    border: 0px solid black;\n"
"}")
        self.lineEdit_import_style.setObjectName("lineEdit_import_style")
        self.horizontalLayout_5.addWidget(self.lineEdit_import_style)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_content_img = QtWidgets.QLabel(self.centralwidget)
        self.label_content_img.setMinimumSize(QtCore.QSize(340, 340))
        self.label_content_img.setMaximumSize(QtCore.QSize(340, 340))
        self.label_content_img.setAutoFillBackground(False)
        self.label_content_img.setStyleSheet("background-color: rgb(56, 64, 85);")
        self.label_content_img.setText("")
        self.label_content_img.setScaledContents(True)
        self.label_content_img.setObjectName("label_content_img")
        self.verticalLayout.addWidget(self.label_content_img)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.label_style_img = QtWidgets.QLabel(self.centralwidget)
        self.label_style_img.setMinimumSize(QtCore.QSize(340, 340))
        self.label_style_img.setMaximumSize(QtCore.QSize(340, 340))
        self.label_style_img.setAutoFillBackground(False)
        self.label_style_img.setStyleSheet("background-color: rgb(56, 64, 85);")
        self.label_style_img.setText("")
        self.label_style_img.setScaledContents(True)
        self.label_style_img.setObjectName("label_style_img")
        self.verticalLayout_5.addWidget(self.label_style_img)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_generated_img = QtWidgets.QLabel(self.centralwidget)
        self.label_generated_img.setMinimumSize(QtCore.QSize(340, 340))
        self.label_generated_img.setMaximumSize(QtCore.QSize(340, 340))
        self.label_generated_img.setAutoFillBackground(False)
        self.label_generated_img.setStyleSheet("background-color: rgb(56, 64, 85);")
        self.label_generated_img.setText("")
        self.label_generated_img.setScaledContents(True)
        self.label_generated_img.setObjectName("label_generated_img")
        self.verticalLayout_2.addWidget(self.label_generated_img)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.comboBox_model = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_model.setMinimumSize(QtCore.QSize(140, 25))
        self.comboBox_model.setMaximumSize(QtCore.QSize(140, 25))
        self.comboBox_model.setStyleSheet("QComboBox {\n"
"    border-radius: 4px;\n"
"    background-color:rgb(83, 89, 110);\n"
"    color:white;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView { color: white; }\n"
"\n"
"QComboBox:disabled {\n"
"    border-radius: 4px;\n"
"    background-color:rgb(83, 89, 110);\n"
"    color:rgb(200, 200, 200);\n"
"    border: 0px solid black;\n"
"}")
        self.comboBox_model.setObjectName("comboBox_model")
        self.comboBox_model.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_model)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.lineEdit_content_weight = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_content_weight.setEnabled(True)
        self.lineEdit_content_weight.setMinimumSize(QtCore.QSize(80, 25))
        self.lineEdit_content_weight.setMaximumSize(QtCore.QSize(80, 25))
        self.lineEdit_content_weight.setStyleSheet("QLineEdit {\n"
"    border-radius: 4px;\n"
"    background-color:rgb(83, 89, 110);\n"
"    color:white;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    border-radius: 4px;\n"
"    background-color:rgb(83, 89, 110);\n"
"    color:rgb(200, 200, 200);\n"
"    border: 0px solid black;\n"
"}")
        self.lineEdit_content_weight.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_content_weight.setObjectName("lineEdit_content_weight")
        self.horizontalLayout_3.addWidget(self.lineEdit_content_weight)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.lineEdit_style_weight = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_style_weight.setEnabled(True)
        self.lineEdit_style_weight.setMinimumSize(QtCore.QSize(80, 25))
        self.lineEdit_style_weight.setMaximumSize(QtCore.QSize(80, 25))
        self.lineEdit_style_weight.setStyleSheet("QLineEdit {\n"
"    border-radius: 4px;\n"
"    background-color:rgb(83, 89, 110);\n"
"    color:white;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    border-radius: 4px;\n"
"    background-color:rgb(83, 89, 110);\n"
"    color:rgb(200, 200, 200);\n"
"    border: 0px solid black;\n"
"}")
        self.lineEdit_style_weight.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_style_weight.setObjectName("lineEdit_style_weight")
        self.horizontalLayout_3.addWidget(self.lineEdit_style_weight)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.lineEdit_iterations = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_iterations.setEnabled(True)
        self.lineEdit_iterations.setMinimumSize(QtCore.QSize(80, 25))
        self.lineEdit_iterations.setMaximumSize(QtCore.QSize(80, 25))
        self.lineEdit_iterations.setStyleSheet("QLineEdit {\n"
"    border-radius: 4px;\n"
"    background-color:rgb(83, 89, 110);\n"
"    color:white;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    border-radius: 4px;\n"
"    background-color:rgb(83, 89, 110);\n"
"    color:rgb(200, 200, 200);\n"
"    border: 0px solid black;\n"
"}")
        self.lineEdit_iterations.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_iterations.setObjectName("lineEdit_iterations")
        self.horizontalLayout_3.addWidget(self.lineEdit_iterations)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.toolButton_process = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_process.setMinimumSize(QtCore.QSize(100, 38))
        self.toolButton_process.setMaximumSize(QtCore.QSize(100, 38))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolButton_process.setFont(font)
        self.toolButton_process.setStyleSheet("QToolButton {\n"
"    color:white; \n"
"    background:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0,         stop:0 rgba(32, 38, 52, 255), \n"
"        stop:1 rgba(91, 99, 120, 255));\n"
"    border: 2px solid black;\n"
"    border-radius: 8px;\n"
"}")
        self.toolButton_process.setObjectName("toolButton_process")
        self.horizontalLayout_4.addWidget(self.toolButton_process)
        self.toolButton_export = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_export.setMinimumSize(QtCore.QSize(100, 38))
        self.toolButton_export.setMaximumSize(QtCore.QSize(100, 38))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolButton_export.setFont(font)
        self.toolButton_export.setStyleSheet("QToolButton {\n"
"    color:white; \n"
"    background:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0,         stop:0 rgba(32, 38, 52, 255), \n"
"        stop:1 rgba(91, 99, 120, 255));\n"
"    border: 2px solid black;\n"
"    border-radius: 8px;\n"
"}")
        self.toolButton_export.setObjectName("toolButton_export")
        self.horizontalLayout_4.addWidget(self.toolButton_export)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        Application.setCentralWidget(self.centralwidget)

        self.retranslateUi(Application)
        QtCore.QMetaObject.connectSlotsByName(Application)

    def retranslateUi(self, Application):
        _translate = QtCore.QCoreApplication.translate
        Application.setWindowTitle(_translate("Application", "MainWindow"))
        self.toolButton_import_content.setText(_translate("Application", "Import Content"))
        self.toolButton_import_style.setText(_translate("Application", "Import Style"))
        self.label_3.setText(_translate("Application", "Content Image"))
        self.label_7.setText(_translate("Application", "Style Image"))
        self.label_4.setText(_translate("Application", "Generated Image"))
        self.label_6.setText(_translate("Application", "Model"))
        self.comboBox_model.setItemText(0, _translate("Application", "VGG19"))
        self.label_8.setText(_translate("Application", "content_weight"))
        self.lineEdit_content_weight.setText(_translate("Application", "1"))
        self.label_9.setText(_translate("Application", "style_weight"))
        self.lineEdit_style_weight.setText(_translate("Application", "1000000"))
        self.label_5.setText(_translate("Application", "Iterations"))
        self.lineEdit_iterations.setText(_translate("Application", "300"))
        self.toolButton_process.setText(_translate("Application", "Process"))
        self.toolButton_export.setText(_translate("Application", "Export"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Application = QtWidgets.QMainWindow()
    ui = Ui_Application()
    ui.setupUi(Application)
    Application.show()
    sys.exit(app.exec_())
